version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/docker_rails'
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysql'
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
