version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/docker_rails'
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysql'
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
